FROM centos:centos6
MAINTAINER Jean-François Roche <jfroche@affinitic.be>
RUN yum -y install git
RUN yum -y install rpm-build
RUN yum -y install yum-utils
RUN yum -y install rpmdevtools
RUN yum -y install wget
ENV HOME /root
WORKDIR /root/
RUN echo '%_topdir %(echo $HOME)/rpmbuild' > /root/.rpmmacros
RUN mkdir $HOME/rpmbuild
ADD build24.sh /root/build24.sh
RUN chmod +x /root/build24.sh
ADD python-opt-2.4.6-1.spec /root/rpmbuild/SPECS/python-opt-2.4.6-1.spec
RUN chown root:root /root/rpmbuild/SPECS/python-opt-2.4.6-1.spec
RUN /root/build24.sh
RUN rpm -ivh /root/rpmbuild/RPMS/x86_64/python24-opt-2.4.6-1.x86_64.rpm
RUN /opt/python2.4.6/bin/python2.4 -c 'import _ssl'
RUN /opt/python2.4.6/bin/python2.4 -c 'import zlib'
RUN /opt/python2.4.6/bin/python2.4 -c 'import crypt'
RUN /opt/python2.4.6/bin/python2.4 -c 'import gzip'

